export class DungeonNodeStatus {
  static OPEN_DOOR = 0;
  static SK_LOCKED = 1;
  static BK_LOCKED = 2;
  static ITEM_LOCKED = 3;
  static BIG_CHEST = 4;
  static VIEWABLE_CLOSED_CHEST = 5;
  static CLOSED_CHEST = 6;
  static OPEN_CHEST = 7;
  static OPEN_BIG_CHEST = 8;
  static BOSS = 9;
  static GROUND_KEY = 10;
  static COLLECTED_GROUND_KEY = 11;
  static SWITCH = 12;
  static WATER_SWITCH = 13;
  static BLIND_RESCUE = 14;
  static TT_BOMB_FLOOR = 15;
  static SWITCH_FLIPPED = 16;
  static BLIND_RESCUED = 17;
  static TT_BOMB_FLOOR_DONE = 18;
  static WATER_SWITCH_FLIPPED = 19;
}
